[package]
name = "input-reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gilrs = "0.9.0"
fps_counter = "2.0.0"
tui = "0.18"
crossterm = "0.23"
